---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data

```{R load libraries, echo = TRUE, results = "hide", message = FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)
library(mice)

```

```{R load data, echo = TRUE, warning = FALSE}
if (!file.exists("activity.csv")) {unzip("activity.zip", exdir = "./") }

activity <- tbl_df(read.csv("activity.csv", header = TRUE)) %>%
                na.omit() %>% # omit missing values
                mutate(date = ymd(date))
 
```


## What is mean total number of steps taken per day?

```{R, echo = TRUE, warning = FALSE}
dailySteps <- group_by(activity, date) %>%
                summarize(sum(steps), mean(steps), median(steps))
names(dailySteps) = make.names(names(dailySteps))

#histogram of the total number of steps taken each day 
qplot(sum.steps., data = dailySteps, ylab="Days")+geom_histogram()+stat_bin(bins=10)

# calc mean & median
dailyMean <- mean(dailySteps$sum.steps., na.rm=TRUE)
dailyMedian <- median(dailySteps$sum.steps., na.rm=TRUE)
```

mean of the total number of steps taken per day: `r dailyMean`  
median of the total number of steps taken per day: `r dailyMedian`


## What is the average daily activity pattern?
```{R, echo = TRUE}
activity <- ungroup(activity) %>% group_by(interval) 
intervalSummary <- summarize(activity, mean(steps))
names(intervalSummary) = make.names(names(intervalSummary))
qplot(interval, mean.steps., data = intervalSummary, ylab="Steps", main="Average number of steps taken")+geom_line()

interval_max <- unlist(intervalSummary[which.max(intervalSummary$mean.steps.),1])

```
Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps? Answer: **`r interval_max`**  
The plot tells that most average steps taken in the morning.  


## Imputing missing values

```{R, echo=TRUE, results="hide", message = FALSE, warning=FALSE, cache= TRUE}
activity2 <- tbl_df(read.csv("activity.csv", header = TRUE)) 
missingValues <- activity2[!complete.cases(activity2),] #subset all obs with missing data

#impute missing data using pmm: predictive mean matching comes with "mice" package
imputedData <- mice(activity2, m=1, maxit=10,method="pmm", seed=500) 
activity2 <- complete(imputedData,1) %>%
                mutate(date = ymd(date))
                
# summarize
dailySteps2 <- group_by(activity2,date) %>%
                summarize(AverageSteps=sum(steps))

# plot
qplot(AverageSteps, data = dailySteps2,ylab="Days")+geom_histogram()+stat_bin(bins=10)
# calc mean & median
dailyMean <- mean(dailySteps2$AverageSteps, na.rm=TRUE)
dailyMedian <- median(dailySteps2$AverageSteps, na.rm=TRUE)

```

Calculate and report the total number of missing values in the dataset: **`r nrow(missingValues)`**  
Mean & median after data being imputed: 
mean of the total number of steps taken per day: `r dailyMean`  
median of the total number of steps taken per day: `r dailyMedian`

## Are there differences in activity patterns between weekdays and weekends?

```{R}
activity2 <- mutate(activity2, Weekday =wday(date,label=T))
activity2$Weekday <- sub("Sun|Sat", "Weekend", activity2$Weekday)
activity2$Weekday <- sub("Mon|Tues|Wed|Thurs|Fri", "Weekday", activity2$Weekday)

intervalSummary2 <- group_by(activity2,Weekday, interval) %>% summarize(AverageSteps=mean(steps))
qplot(interval, AverageSteps, data=intervalSummary2,facets=.~Weekday) + geom_line()

```

From the plots, it's abvious that:  
* on weekdays: there is a peak at interval `r intervalSummary2[which.max(intervalSummary2$AverageSteps),2]`, which is about 8 O'Clock in the morning.  
* on weekends: much more steps during day time, from 8AM till 8PM.  